# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d81bcbb25ebf98b0168c4d999e5a6d1fa4a6dcf9cb9853fed8545755f3ddadcc7e0194bd5ee53b3c326d86853be5f11010a72fbf39cebed9aa9f9f16ecad431

test:
  secret_key_base: 02bb03597bc26862ce8f0cf5e1448a311f43bcec7bbc7cc8aee8dad0b233a4f5c6c4dcb3fb61fbddbdc182653bc1752b577ae362d33cc1b3fe1ab9196b751b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
